name: First action
on : [push]

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
          - name: list of directory
            run: ls
    build:
        runs-on: ubuntu-latest

        steps:
          - name: checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 0

          - name: Set up JDK
            uses: actions/setup-java@v1
            with:
              java-version: 8

          - name: Make gradlew executable
            run: chmod +x gradlew              

          - name: Build with Gradle
            id: build
            run: ./gradlew build

          - name: Docker login
            uses: azure/docker-login@v1
            with:
                login-server: ${{secrets.ACR_DEV_ENV_URL}}
                username: ${{ secrets.ACR_DEV_ENV_USERNAME }}
                password: ${{ secrets.ACR_DEV_ENV_PASSWORD }}



